title: "Kanegae"
author: "Yuri Henry Takashi Queiroz Kanegae"
description: "Sobre os ombros de gigantes."

email: "yurikanegae@gmail.com"
github_username: "yurikanegae"
linkedin_username: "yurikanegae"

theme: "minima"

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
